name: hdf5-examples

# Controls when the action will run. 
#Triggers the workflow on push or pull requests.
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that
# can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        name: ["macOS Latest"]
        include:
          - name: "macOS Latest"
            artifact: "macOS.tar.xz"
            os: macos-latest
            parallel: disable
            fortran: with
            hdf5: with
            tools: with

    name: ${{ matrix.name }}
    # The type of runner that the job will run on.
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    # Steps represent a sequence of tasks that will be executed 
    # as part of the job.
    steps:

    - name: Install Dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # Set env vars
        echo "OS_NAME=macOS" >> $GITHUB_ENV
        # Use the newest stable gcc compiler
        brew update
        brew install hdf5
        brew install cmake

 # Checks-out the repository under $GITHUB_WORKSPACE so the job can access it.
    - name: Get Sources
      uses: actions/checkout@v2

##################################
# BUILD AND TEST HDF5-examples
##################################

    - name: build (autotools) and check
      run: |
        ./configure
        make
        make check
      shell: bash

#    - name: build (cmake)
#      run: |
#        mkdir build; cd build
#        cmake -D FORTRAN_INTERFACE=ON -D CMAKE_BUILD_TYPE=Release ..
#        make
#      shell: bash
