name: hdf5-examples

# Controls when the action will run. 
#Triggers the workflow on push or pull requests.
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that
# can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux-build:
    strategy:
      matrix:
        name: ["Ubuntu Latest GCC"]
        include:
          - name: "Ubuntu Latest GCC"
            artifact: "Linux.tar.xz"
            os: ubuntu-latest

    name: ${{ matrix.name }}
    # The type of runner that the job will run on.
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    # Steps represent a sequence of tasks that will be executed 
    # as part of the job.
    steps:
    - name: Install Dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -qq libhdf5-dev
        sudo apt-get install -qq hdf5-tools
        cat /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.settings
        echo  "HDF5_HOME=/usr/include/hdf5/serial,/usr/lib/x86_64-linux-gnu/hdf5/serial,/usr/bin" >> $GITHUB_ENV
        # Set env vars
        #echo "PATH=":$PATH"
        echo "CC=h5cc" >> $GITHUB_ENV
        echo "FC=h5fc" >> $GITHUB_ENV
        
 # Checks-out the repository under $GITHUB_WORKSPACE so the job can access it.
    - name: Get Sources
      uses: actions/checkout@v2

##################################
# BUILD AND TEST HDF5-examples
##################################

    - name: build (autotools) and check
      run: |
        ./configure
        make
        make check
      shell: bash

#    - name: build (cmake)
#      run: |
#        mkdir build; cd build
#        cmake -D FORTRAN_INTERFACE=ON -D CMAKE_BUILD_TYPE=Release ..
#        make
#      shell: bash
